### PR TITLE
Create Russian.php

### PR DESCRIPTION
**Pull request by veselcraft**

### CODE REVIEW

**Comment by WerySkok** [comment]
You used only two plural forms, when there are three of them in russian.

**Comment by veselcraft** [comment]
ik

**Comment by rollerozxa** [comment]
> You used only two plural forms, when there are three of them in russian.

Hm... That would probably need some additional functionality added to the library to work.

**Comment by WerySkok** [comment]
Here are some helpful links from CLDR:
* http://cldr.unicode.org/index/cldr-spec/plural-rules
* https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
